server:  
  port: 8057

spring:
  application:
    name: animalsfeingclient

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

microservicio:
  contact:
    name: api-gateway
    findAllUrl: http://${microservicio.contact.name}/animals
    saveUrl: http://${microservicio.contact.name}/animals
    deleteUrl: http://${microservicio.contact.name}/animals/{id}
